Error: autenticaÔøΩÔøΩo do tipo senha falhou para o usuÔøΩrio "postgres"
    at Q (https://local.drizzle.studio/index.js:101938:6775)
    at async Object.query (https://local.drizzle.studio/index.js:101933:354551)
    at async Promise.all (index 0)
    at async x8n (https://local.drizzle.studio/index.js:1180:98)
    at async G5n (https://local.drizzle.studio/index.js:1519:15149)
    at async pull (https://local.drizzle.studio/index.js:1519:33934)

npm run studio

$ npm run studio

> api-node@1.0.0 studio
> node src/scripts/drizzle/start-studio.js

üöÄ Iniciando Drizzle Studio...

üîç Verificando processos na porta 4983...
üéØ Encontrados 1 processo(s) na porta 4983: 10804
üíÄ Processo 10804 finalizado com sucesso
‚úÖ Porta 4983 liberada com sucesso

üîÑ Iniciando novo Drizzle Studio...
No config path provided, using default 'drizzle.config.ts'
Reading config file 'C:\Users\dsoliveira\Documents\Github\api-node\drizzle.config.ts'
[dotenv@17.2.2] injecting env (0) from .env -- tip: üì° observe env with Radar: https://dotenvx.com/radar
Using 'pg' driver for database querying

 Warning  Drizzle Studio is currently in Beta. If you find anything that is not working as expected or should be improved, feel free to create an issue on GitHub: https://github.com/drizzle-team/drizzle-kit-mirror/issues/new or write to us on Discord: https://discord.gg/WcRKz2FFxN                         

Drizzle Studio is up and running on https://local.drizzle.studio
error: autenticaÔøΩÔøΩo do tipo senha falhou para o usuÔøΩrio "postgres"
    at C:\Users\dsoliveira\Documents\Github\api-node\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async proxy (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:80615:26)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91755:26
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89597:9
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async cors2 (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91236:9)
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91690:9 {
  length: 113,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '324',
  routine: 'auth_failed'
}
error: autenticaÔøΩÔøΩo do tipo senha falhou para o usuÔøΩrio "postgres"
    at C:\Users\dsoliveira\Documents\Github\api-node\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async proxy (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:80615:26)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91755:26
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89597:9
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async cors2 (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91236:9)
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91690:9 {
  length: 113,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '324',
  routine: 'auth_failed'
}
error: autenticaÔøΩÔøΩo do tipo senha falhou para o usuÔøΩrio "postgres"
    at C:\Users\dsoliveira\Documents\Github\api-node\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async proxy (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:80615:26)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91755:26
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89597:9
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async cors2 (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91236:9)
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91690:9 {
  length: 113,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '324',
  routine: 'auth_failed'
}
error: autenticaÔøΩÔøΩo do tipo senha falhou para o usuÔøΩrio "postgres"
    at C:\Users\dsoliveira\Documents\Github\api-node\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async proxy (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:80615:26)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91755:26
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89597:9
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async cors2 (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91236:9)
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91690:9 {
  length: 113,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '324',
  routine: 'auth_failed'
}
error: autenticaÔøΩÔøΩo do tipo senha falhou para o usuÔøΩrio "postgres"
    at C:\Users\dsoliveira\Documents\Github\api-node\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async proxy (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:80615:26)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91755:26
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89597:9
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async cors2 (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91236:9)
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91690:9 {
  length: 113,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '324',
  routine: 'auth_failed'
}
error: autenticaÔøΩÔøΩo do tipo senha falhou para o usuÔøΩrio "postgres"
    at C:\Users\dsoliveira\Documents\Github\api-node\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async proxy (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:80615:26)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91755:26
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89597:9
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async cors2 (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91236:9)
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91690:9 {
  length: 113,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '324',
  routine: 'auth_failed'
}
error: autenticaÔøΩÔøΩo do tipo senha falhou para o usuÔøΩrio "postgres"
    at C:\Users\dsoliveira\Documents\Github\api-node\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async proxy (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:80615:26)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91755:26
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89597:9
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async cors2 (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91236:9)
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91690:9 {
  length: 113,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '324',
  routine: 'auth_failed'
}
error: autenticaÔøΩÔøΩo do tipo senha falhou para o usuÔøΩrio "postgres"
    at C:\Users\dsoliveira\Documents\Github\api-node\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async proxy (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:80615:26)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91755:26
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89597:9
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async cors2 (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91236:9)
    at async dispatch (C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:89663:21)
    at async C:\Users\dsoliveira\Documents\Github\api-node\node_modules\drizzle-kit\bin.cjs:91690:9 {
  length: 113,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '324',
  routine: 'auth_failed'
}

üõë Finalizando Drizzle Studio...
